import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import Anthropic from "@anthropic-ai/sdk";
import OpenAI from "openai";
import { AppDispatch, RootState } from ".";
import { readFile, writeFile } from "../services/fsService";

/*
  Anthropic.Message {
    id: string;
    role: 'assistant';
    content: Array<ContentBlock>; // [{ "type": "text", "text": "Hi, I'm Claude." }] 
    model: Model;
    stop_reason: 'end_turn' | 'max_tokens' | 'stop_sequence' | 'tool_use' | null;
    stop_sequence: string | null;
    type: 'message';
    usage: Usage;
  }
  type ContentBlock = TextBlock | ToolUseBlock;
  interface TextBlock {
    text: string;
    type: 'text';
  }
  export interface ToolUseBlock {
    id: string;
    input: unknown;
    name: string;
    type: 'tool_use';
  }
  export type Model =
    | (string & {})
    | 'claude-3-5-sonnet-20240620'
    | 'claude-3-opus-20240229'
    | 'claude-3-sonnet-20240229'
    | 'claude-3-haiku-20240307'
    | 'claude-2.1'
    | 'claude-2.0'
    | 'claude-instant-1.2';
  export interface Usage {
    input_tokens: number;
    output_tokens: number;
  }


  OpenAI.ChatCompletionMessage {
    content: string | null;
    role: 'assistant';
    tool_calls?: Array<ChatCompletionMessageToolCall>;
  }
  export interface ChatCompletionMessageToolCall {
    id: string;
    function: ChatCompletionMessageToolCall.Function;
    type: 'function';
  }
  export interface Function {
    // The arguments to call the function with, as generated by the model in JSON
    // format. Note that the model does not always generate valid JSON, and may
    // hallucinate parameters not defined by your function schema. Validate the
    // arguments in your code before calling your function.
    arguments: string;
    name: string;
  }
*/

export interface IThreadSystemMessage {
  role: "system";
  content: string;
}

export interface IThreadUserMessage {
  role: "user";
  content: string;
}

export type IThreadMessage =
  | IThreadSystemMessage
  | IThreadUserMessage
  | Anthropic.Message
  | OpenAI.ChatCompletionMessage;

export interface IThreadState {
  threadPaths: string[];
  threadPath: string | null;
  threadMessages: Array<IThreadMessage>;
  threadError: string | null;
  processing: boolean;
}

const defaultInitialState: IThreadState = {
  threadPaths: [],
  threadPath: null,
  threadMessages: [],
  threadError: null,
  processing: false,
};

const threadSlice = createSlice({
  name: "thread",
  initialState: defaultInitialState,
  reducers: {
    setThreadPaths: (
      state,
      action: PayloadAction<IThreadState["threadPaths"]>
    ) => {
      state.threadPaths = action.payload;
    },
    setThreadPath: (
      state,
      action: PayloadAction<IThreadState["threadPath"]>
    ) => {
      state.threadPath = action.payload;
    },
    setThreadMessages: (
      state,
      action: PayloadAction<IThreadState["threadMessages"]>
    ) => {
      state.threadMessages = action.payload;
    },
    setThreadError: (
      state,
      action: PayloadAction<IThreadState["threadError"]>
    ) => {
      state.threadError = action.payload;
    },
    setProcessing: (
      state,
      action: PayloadAction<IThreadState["processing"]>
    ) => {
      state.processing = action.payload;
    },
    setProcessingThread: (state) => {
      state.processing = true;
      state.threadError = null;
    },
    setProcessingThreadSuccess: (
      state,
      action: PayloadAction<IThreadMessage[]>
    ) => {
      state.processing = false;
      state.threadMessages = action.payload;
      state.threadError = null;
    },
    setProcessingThreadFailure: (state, action: PayloadAction<string>) => {
      state.processing = false;
      state.threadError = action.payload;
    },
  },
});

export const {
  setThreadPaths,
  setThreadPath,
  setThreadMessages,
  setThreadError,
  setProcessing,
  setProcessingThread,
  setProcessingThreadSuccess,
  setProcessingThreadFailure,
} = threadSlice.actions;

export default threadSlice.reducer;

const createThreadName = () => `threads/thread-${Date.now()}.json`;

const handleError = (
  error: unknown,
  prefix?: string,
  action?: (msg: string) => void
) => {
  const errorMessage = `${prefix ? prefix : ""} ${
    typeof error === "string" ? error : (error as Error).message
  }`;
  console.log(errorMessage);
  if (action) action(errorMessage);
};

export const loadThread =
  (threadPath: string) =>
  async (dispatch: AppDispatch, getState: () => RootState) => {
    try {
      dispatch(setProcessingThread());
      dispatch(setThreadPath(threadPath));
      const activeProjectPath = getState().projects.activeProjectPath;
      const path = `${activeProjectPath}/${threadPath}`;
      const result = await readFile(path);
      const threadMessages: IThreadMessage[] = JSON.parse(result);
      dispatch(setProcessingThreadSuccess(threadMessages));
    } catch (error) {
      handleError(error, "Error loadThread:", (msg) =>
        dispatch(setProcessingThreadFailure(msg))
      );
    }
  };

export const saveThread =
  (threadPath: string, threadMessages: IThreadMessage[]) =>
  async (dispatch: AppDispatch, getState: () => RootState) => {
    try {
      dispatch(setProcessingThread());
      const activeProjectPath = getState().projects.activeProjectPath;
      const path = `${activeProjectPath}/${threadPath}`;
      await writeFile(path, JSON.stringify(threadMessages, null, 2));
      dispatch(setProcessing(false));
    } catch (error) {
      handleError(error, "Error saveThread:", (msg) =>
        dispatch(setThreadError(msg))
      );
    }
  };

export const createThread = () => async (dispatch: AppDispatch) => {
  try {
    dispatch(setProcessingThread());
    const threadPath = createThreadName();
    dispatch(setThreadPath(threadPath));
    dispatch(setProcessing(false));
  } catch (error) {
    handleError(error, "Error createThread:", (msg) =>
      dispatch(setThreadError(msg))
    );
  }
};
